-- Auto-generated from config/security/rpc-allowlist.json
-- (Update via the allowlist file, then regenerate.)

BEGIN;

SELECT plan(2);

-- Ensure anon can execute only the anon allowlist in the public schema.
SELECT is(
  (
    SELECT COALESCE(array_agg(DISTINCT p.proname::text ORDER BY p.proname::text), ARRAY[]::text[])
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND has_function_privilege('anon', p.oid, 'EXECUTE')
  ),
  ARRAY[
-- BEGIN RPC_ALLOWLIST_ANON_TEST
        'resolve_service_area',
        'support_article_get_public_v1',
        'support_articles_list_public_v1',
        'trip_share_view_public_v1'
-- END RPC_ALLOWLIST_ANON_TEST
  ]::text[],
  'Anon role can only EXECUTE allowlisted public RPCs'
);

-- Ensure authenticated can execute only the authenticated allowlist in the public schema.
SELECT is(
  (
    SELECT COALESCE(array_agg(DISTINCT p.proname::text ORDER BY p.proname::text), ARRAY[]::text[])
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND has_function_privilege('authenticated', p.oid, 'EXECUTE')
  ),
  ARRAY[
-- BEGIN RPC_ALLOWLIST_AUTHENTICATED_TEST
        'achievement_claim',
        'admin_approve_role_change_request_v1',
        'admin_cash_agent_create_v1',
        'admin_cash_agent_list_v1',
        'admin_cash_agent_next_doc_no_v1',
        'admin_cash_agent_set_active_v1',
        'admin_cashbox_close_day_v1',
        'admin_cashbox_reconciliation_v1',
        'admin_clone_pricing_config_v1',
        'admin_create_role_change_request_v1',
        'admin_create_service_area_bbox_v2',
        'admin_create_service_area_bbox_v3',
        'admin_generate_gift_codes_v1',
        'admin_gift_codes_list_v1',
        'admin_grant_user_v1',
        'admin_has_permission',
        'admin_list_admin_access_v1',
        'admin_list_role_change_requests_v1',
        'admin_list_role_change_requests_v2',
        'admin_list_roles_v1',
        'admin_maps_provider_capability_list_v1',
        'admin_maps_provider_capability_set_v1',
        'admin_maps_provider_health_list_v1',
        'admin_maps_provider_health_reset_v1',
        'admin_maps_provider_list_v1',
        'admin_maps_provider_list_v2',
        'admin_maps_provider_list_v3',
        'admin_maps_provider_set_v1',
        'admin_maps_provider_set_v2',
        'admin_maps_provider_set_v3',
        'admin_maps_requests_list_v1',
        'admin_maps_requests_list_v2',
        'admin_maps_requests_stats_v1',
        'admin_merchant_commission_clear_v1',
        'admin_merchant_commission_clear_v2',
        'admin_merchant_commission_list_v1',
        'admin_merchant_commission_list_v2',
        'admin_merchant_commission_set_v1',
        'admin_merchant_commission_set_v2',
        'admin_merchant_get_v1',
        'admin_merchant_promotions_list_v1',
        'admin_merchants_list_v1',
        'admin_my_roles',
        'admin_order_get_v1',
        'admin_order_set_status_v1',
        'admin_orders_list_v1',
        'admin_permissions',
        'admin_platform_fee_list_v1',
        'admin_platform_fee_set_v1',
        'admin_reconciliation_daily_v1',
        'admin_record_ride_refund',
        'admin_record_ride_refund_v2',
        'admin_referral_campaigns_list_v1',
        'admin_reject_role_change_request_v1',
        'admin_revoke_user_v1',
        'admin_ridecheck_escalate',
        'admin_ridecheck_resolve',
        'admin_role_keys_have_permission',
        'admin_service_area_delete_v1',
        'admin_service_area_get_v1',
        'admin_service_area_upsert_v1',
        'admin_service_areas_list_v1',
        'admin_set_default_pricing_config_v1',
        'admin_set_merchant_promotion_active_v1',
        'admin_set_merchant_status',
        'admin_set_merchant_status_v1',
        'admin_set_user_roles_v1',
        'admin_settlement_approve_payment_request_v1',
        'admin_settlement_approve_payout_request_v1',
        'admin_settlement_list_accounts_v1',
        'admin_settlement_list_entries_v1',
        'admin_settlement_list_payment_requests_v1',
        'admin_settlement_list_payout_requests_v1',
        'admin_settlement_record_payout_v1',
        'admin_settlement_record_payout_v2',
        'admin_settlement_record_receipt_v1',
        'admin_settlement_record_receipt_v2',
        'admin_settlement_reject_payment_request_v1',
        'admin_settlement_reject_payout_request_v1',
        'admin_settlement_statement_entries_v1',
        'admin_settlement_statement_summary_v1',
        'admin_support_article_get_v1',
        'admin_support_article_upsert_v1',
        'admin_support_articles_list_v1',
        'admin_support_section_upsert_v1',
        'admin_support_sections_list_v1',
        'admin_support_ticket_add_internal_note_v1',
        'admin_support_ticket_assign_v1',
        'admin_support_ticket_get_v1',
        'admin_support_ticket_post_message_v1',
        'admin_support_ticket_set_status_v1',
        'admin_support_tickets_list_v1',
        'admin_update_pricing_config_caps',
        'admin_update_referral_campaign_v1',
        'admin_update_ride_incident',
        'admin_upsert_service_area_geojson_v1',
        'admin_void_gift_code_v1',
        'admin_wallet_integrity_snapshot',
        'admin_withdraw_approve',
        'admin_withdraw_mark_paid',
        'admin_withdraw_reject',
        'cancel_ride_request',
        'check_destination_lock',
        'create_ride_incident',
        'dispatch_accept_ride_user',
        'dispatch_match_ride_user',
        'driver_claim_order_delivery',
        'driver_hotspots_v1',
        'driver_location_upsert_user_v1',
        'driver_settlement_get_my_account_v1',
        'driver_settlement_list_entries_v1',
        'driver_settlement_list_payment_requests_v1',
        'driver_settlement_list_payout_requests_v1',
        'driver_settlement_request_payment_v1',
        'driver_settlement_request_payout_v1',
        'driver_settlement_statement_entries_v1',
        'driver_settlement_statement_summary_v1',
        'drivers_nearby_user_v1',
        'family_accept_invite',
        'family_create',
        'family_invite_teen',
        'family_update_policy',
        'get_active_shift',
        'get_applicable_pricing_rules',
        'get_live_activity_throttle_config',
        'get_my_app_context',
        'get_nearby_hotspots',
        'get_today_forecast',
        'get_user_membership',
        'get_user_passkeys',
        'guardian_trip_track_user_v1',
        'is_admin',
        'merchant_chat_get_or_create_thread',
        'merchant_chat_list_messages',
        'merchant_chat_mark_read',
        'merchant_order_create',
        'merchant_order_get_or_create_chat_thread',
        'merchant_order_request_delivery',
        'merchant_order_set_status',
        'merchant_settlement_get_my_account_v1',
        'merchant_settlement_list_entries_v1',
        'merchant_settlement_list_payment_requests_v1',
        'merchant_settlement_list_payout_requests_v1',
        'merchant_settlement_request_payment_v1',
        'merchant_settlement_request_payout_v1',
        'merchant_settlement_statement_entries_v1',
        'merchant_settlement_statement_summary_v1',
        'nearby_available_drivers_v1',
        'nearby_available_drivers_v2',
        'passkey_revoke',
        'redeem_gift_code',
        'referral_apply_code',
        'referral_claim',
        'referral_status',
        'resolve_service_area',
        'ride_chat_get_or_create_thread',
        'ride_chat_list_user_v1',
        'ride_chat_mark_read',
        'ride_chat_send_message',
        'ride_intent_create_user_v1',
        'ride_pickup_pin_mark_verified',
        'ride_pickup_pin_record_failure',
        'ride_verify_pickup_pin',
        'ridecheck_respond_user',
        'scheduled_ride_cancel_user_v1',
        'scheduled_ride_create_user_v1',
        'scheduled_ride_list_user_v1',
        'search_catalog_v1',
        'set_my_active_role',
        'submit_ride_rating',
        'support_article_get_public_v1',
        'support_articles_list_public_v1',
        'support_categories_list_user_v1',
        'support_ticket_create_user_v1',
        'support_ticket_get_user_v1',
        'support_ticket_list_user_v1',
        'support_ticket_post_message_user_v1',
        'transition_ride_user_v1',
        'trip_live_activity_register',
        'trip_live_activity_revoke',
        'trip_share_create_user_v1',
        'trip_share_view_public_v1',
        'user_notifications_mark_all_read',
        'user_notifications_mark_read',
        'wallet_cancel_withdraw',
        'wallet_get_my_account',
        'wallet_request_withdraw'
-- END RPC_ALLOWLIST_AUTHENTICATED_TEST
  ]::text[],
  'Authenticated role can only EXECUTE allowlisted public RPCs'
);

SELECT * FROM finish();

ROLLBACK;
