-- Session 15 hardening: make WebAuthn ceremonies verifiable end-to-end (FIXED)
-- - Persist and retrieve challenges (so server can verify)
-- - Store credential metadata recommended by WebAuthn libraries (transports, device type, backed-up state)

set lock_timeout = '5s';
set statement_timeout = '60s';

begin;

-- 1) Store more WebAuthn metadata (safe additive change)
alter table if exists public.user_passkeys
  add column if not exists transports text[] null,
  add column if not exists webauthn_device_type text null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'user_passkeys_webauthn_device_type_check'
  ) then
    alter table public.user_passkeys
      add constraint user_passkeys_webauthn_device_type_check
      check (webauthn_device_type is null or webauthn_device_type in ('singleDevice', 'multiDevice'));
  end if;
end $$;

-- 2) Allow supplying a known challenge (generated by the WebAuthn library)
-- Fixed drop signature to match migration 13
drop function if exists public.webauthn_create_challenge(text, uuid, text, text);

create or replace function public.webauthn_create_challenge(
  p_challenge_type text,
  p_user_id uuid default null,
  p_session_id text default null,
  p_user_agent text default null,
  p_challenge bytea default null
)
returns table (challenge_id uuid, challenge bytea, expires_at timestamptz)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_challenge bytea;
begin
  v_challenge := coalesce(p_challenge, gen_random_bytes(32));

  insert into public.webauthn_challenges (challenge_type, user_id, session_id, user_agent, challenge, expires_at)
  values (p_challenge_type, p_user_id, p_session_id, left(p_user_agent, 500), v_challenge, now() + interval '5 minutes')
  returning id, challenge, expires_at
  into challenge_id, challenge, expires_at;
end;
$$;

revoke all on function public.webauthn_create_challenge(text, uuid, text, text, bytea) from public;
grant execute on function public.webauthn_create_challenge(text, uuid, text, text, bytea) to service_role;

-- 3) Consume challenge AND return its value so the server can verify expectedChallenge
create or replace function public.webauthn_consume_challenge_details(p_challenge_id uuid)
returns table (challenge bytea, user_id uuid, challenge_type text)
language plpgsql
security definer
set search_path = public
as $$
begin
  return query
  update public.webauthn_challenges
    set used_at = now()
  where id = p_challenge_id
    and used_at is null
    and expires_at > now()
  returning webauthn_challenges.challenge, webauthn_challenges.user_id, webauthn_challenges.challenge_type;
end;
$$;

revoke all on function public.webauthn_consume_challenge_details(uuid) from public;
grant execute on function public.webauthn_consume_challenge_details(uuid) to service_role;

-- 4) Extend passkey_register so Edge Functions can store recommended metadata
-- Fixed drop signature to match migration 13 (uuid, bytea, bytea, public.passkey_type, text, bytea, boolean, text, text)
drop function if exists public.passkey_register(uuid, bytea, bytea, public.passkey_type, text, bytea, boolean, text, text);

create or replace function public.passkey_register(
  p_user_id uuid,
  p_credential_id bytea,
  p_public_key bytea,
  p_passkey_type text, -- changed to text for flexibility
  p_friendly_name text default null,
  p_backup_eligible boolean default false,
  p_device_type text default null,
  p_user_agent text default null,
  p_transports text[] default null,
  p_webauthn_device_type text default null,
  p_backup_state boolean default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  insert into public.user_passkeys (
    user_id,
    credential_id,
    public_key,
    passkey_type,
    friendly_name,
    backup_eligible,
    backup_state,
    device_type,
    user_agent,
    transports,
    webauthn_device_type
  ) values (
    p_user_id,
    p_credential_id,
    p_public_key,
    p_passkey_type::public.passkey_type,
    left(p_friendly_name, 120),
    coalesce(p_backup_eligible, false),
    coalesce(p_backup_state, false),
    left(p_device_type, 50),
    left(p_user_agent, 500),
    p_transports,
    p_webauthn_device_type
  )
  returning id into v_id;

  -- Audit log: Fixed table name and column names to match Migration 13
  insert into public.passkey_auth_log(user_id, passkey_id, event_type, success, ip_address, user_agent)
  values (p_user_id, v_id, 'registration', true, inet_client_addr(), left(p_user_agent, 500));

  return v_id;
end;
$$;

grant execute on function public.passkey_register(uuid, bytea, bytea, text, text, boolean, text, text, text[], text, boolean) to service_role;

commit;
;
